### PR TITLE
Add four new built-in rules

### LINKED ISSUE #216: Possible additional rules
There are some rules we've created that I think would be generally useful to others. Would you accept a PR that adds these?

- `arguments-have-descriptions`: Every argument must have a description
- `descriptions-are-capitalized`: All description text must start with a capital letter
- `input-object-fields-sorted-alphabetically`: Fields of an `input` must be listed alphabetically
- `type-fields-sorted-alphabetically`: Fields of a `type` must be listed alphabetically

Definitions:
https://github.com/reactioncommerce/reaction/tree/trunk/.reaction/graphql-linter/rules

### PR DESCRIPTION
**Pull request by aldeed**
Resolves #216 

Adds four additional built-in rules, along with tests and docs for each:
- `arguments-have-descriptions`: Every argument must have a description
- `descriptions-are-capitalized`: All description text must start with a capital letter
- `input-object-fields-sorted-alphabetically`: Fields of an `input` must be listed alphabetically
- `type-fields-sorted-alphabetically`: Fields of a `type` must be listed alphabetically

### CODE REVIEW

**Comment by aldeed** [comment]
Not sure about the TravisCI failure. Tests pass locally for me

**Comment by cjoudrey** [comment]
Exciting! 🎉 Thanks for the contribution! 😄 

> Not sure about the TravisCI failure. Tests pass locally for me

The test failures from the high-level integration test I configured in `.travis.yml`.

Screen Shot 2020-03-31 at 6 09 23 PM

You'll basically need to fix `test/fixtures/valid.graphql` and it should turn green.

**Comment by aldeed** [comment]
@cjoudrey Fixed

**Comment by cjoudrey** [comment]
Thanks again for this contribution @aldeed. ❤️

**Pull request merged**
