### PR TITLE
Add support for node v6 latest

### PR DESCRIPTION
**Pull request by bwillis**

### CODE REVIEW

**Comment by cjoudrey** [comment]
Thanks for the contribution @bwillis! 😄 

Out of curiosity what version of node were you making this change for?

I'm asking because [the test suite currently tests](https://github.com/cjoudrey/graphql-schema-linter/blob/37d6236e5aaffa847d817733959fc09549c8734a/.travis.yml#L3-L4) against latest and latest lts. Did you want to add another version?

**Comment by bwillis** [comment]
> I'm asking because the test suite currently tests against latest and latest lts. Did you want to add another version?

Ah, yeah I guess I wasn't aware what versions were officially supported, I didn't think to look in travis config. We're using an older version, v6 LTS. This looks to be the only issue to support v6 for our purposes, but I can understand that adding support for older versions may bring on additional burden to the project.

**Comment by cjoudrey** [comment]
I don’t mind supporting v6 if that’s all it takes. 😄 I would just suggest adding it to the CI config so we don’t accidentally break it again.

If it ever becomes too much of a burden, we can rethink that decision, but I don’t think we’re doing too much out of the ordinary.

**Comment by bwillis** [comment]
That works:
screen shot 2018-02-07 at 10 36 01 pm

Thoughts on testing with latest v6 vs v6 lts?

**Comment by cjoudrey** [comment]
> Thoughts on testing with latest v6 vs v6 lts?

None that I can think of. Worse case we can adjust later on if this setting doesn't make sense.

Thanks again! 😄

**Comment by bwillis** [comment]
> None that I can think of. Worse case we can adjust later on if this setting doesn't make sense.
👍 

Thank you!

**Comment by cjoudrey** [comment]
This has shipped in v0.0.29. Thanks again! 😄

**Pull request merged**
