### PR TITLE
[WIP] feat: add --fix flag

### PR DESCRIPTION
**Pull request by iamclaytonray**
I don't have too much done but work seems like it will be slowing down within 4 weeks. I'll try to have this completed (with tests) as soon as I can!

### CODE REVIEW

**Comment by iamclaytonray** [comment]
I don't have too much done but work seems like it will be slowing down within 4 weeks. I'll try to have this completed (with tests) as soon as I can!

**Comment by iamclaytonray** [comment]
@cjoudrey - I'm still somewhat new to OSS. I've assumed that I should pull in changes from whatever base branch (usually master) I'm going off of. Is that correct? If not, sorry :/

**Comment by cjoudrey** [comment]
Thanks for the contribution @iamclaytonray 😄! 

> I'm still somewhat new to OSS. I've assumed that I should pull in changes from whatever base branch (usually master) I'm going off of. Is that correct? If not, sorry :/

No worries! Happy to help with your first contribution. 😄 It looks like you based off `master` which is perfect.

>  I know I can access `rule.name` but still don't know how to access `rule.fixable`

That's a really good question. `rule` currently returns a function which is why `rule.name` works (it's returning the name of the function).

I haven't put a whole lot of thought into this issue and to be frank it's a tricky one. 😄

We may want to look into how similar systems like ESLint solve this, but here was my first thought.

I think we need rules to define two functions. One that validates and one that fixes problems.

This means we'll want to have rules to export both of these functions instead of just one.

I'm not entirely sure when `fix` should get called and what _exactly_ it should do, but I'm assuming it will have to manipulate the AST. For example, the `EnumValuesAllCaps` rule would automatically capitalize the `name` of all `EnumValueDefinition` nodes.

Once we've called `fix` on all rules that can be fixed, we'll need to print out the modified AST to the appropriate `.graphql` files. The tricky part here is we might mess with the original formatting, but I don't think this is the end of the world. I'm also wondering if we should leverage `prettier` here or just use GraphQL.js' normal printing methods.

**Comment by iamclaytonray** [comment]
Hmm, yeah, I was thinking something along the same lines. I somewhat was able to check if a rule was fixable or not, with my `isFixable` variable, although, the results weren't as expected. I'll keep digging into this. I think I have to worry about checking which rules can be fixed and which ones can't before I make function calls to manipulate the AST. You can certainly correct me if I am wrong. Thank you for all of your insight and advice! It's super helpful 😄

**Pull request closed without merging**
